<div class="row">
    <div class="col-md-4 offset-md-4">
        <?php if(!empty($loginMsg)): ?>
            <div class="alert alert-danger"><?= $loginMsg ?></div>
        <?php endif; ?>

        <h1 class="text-center">Edit</h1>

        <form action="/users/update/<?= $user['id'] ?>" method="POST" class="border p-4">
            <input type="hidden" name="userId" value="<?= $user['id'] ?>">
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" class="form-control" id="username" name="username" value="<?= $user['username'] ?>" disabled>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" class="form-control" id="password" name="password">
                <?php if(!empty($valiPass)): ?>
                    <span class="text-danger" id="errPass"><?= $valiPass ?></span>
                <?php endif; ?>
            </div>
            <button type="submit" class="btn btn-primary" id="btnRegister">Submit</button>
            <a href="/test/dashboard">Cancel</a>
        </form>
    </div>
</div>



