<div class="row mt-3">
    <div class="col-md-12">
        <h1>Dashboard</h1>
        <h2><?= $_SESSION['username'] ?? '' ?></h2>
        <a href="/test/logout">Logout</a>
    </div>
</div>

<div class="row mt-3">
    <div class="col-md-6 offset-md-3">
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Search" id="keywords">
            <div class="input-group-append">
                <button class="btn btn-success" type="button" id="btnSearch">Search</button>
            </div>
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>#</th>
                <th>username</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <?php if(!empty($users)): ?>
                <?php foreach ($users as $user): ?>
                    <tr>
                        <td><?= $user['id'] ?></td>
                        <td><?= $user['username'] ?></td>
                        <td>
                            <a href="/users/edit/<?= $user['id'] ?>" class="btn btn-primary">Edit</a>
                            <a href="/users/delete/<?= $user['id'] ?>" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="3" CLASS="text-center">NO DATA</td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<script>
    commands.push(function(){
        $('#btnSearch').on('click', function(){
            var keywords = $('#keywords').val().trim();
            keywords = keywords || '';
            window.location.href = base_url + 'test/dashboard?keywords=' + keywords;
        });
    })
</script>