<?php
//echo "<pre>";
//    var_dump($select_categories);
?>

<div class="row mt-5">
    <div class="col-md-6 offset-md-3">
        <?php if (!empty($msgProductErr)): ?>
            <div class="alert alert-danger"><?= $msgProductErr ?></div>
        <?php endif; ?>

        <div class="card">
            <div class="card-header">
                <a href="/products" class="btn btn-secondary">Back</a>
            </div>
            <div class="card-body">
                <form action="/products/edit" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="name">Product</label>
                        <input type="text" class="form-control" name="name" value="<?= $oldName ?? '' ?>">
                        <?php if(!empty($errName)): ?>
                            <span class="text-danger"><?= $errName ?></span>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label for="category_id">Categories</label>
                        <select name="category_id" id="category_id" class="form-control">
                            <option value="">--- Choose Please ---</option>
                            <?php if (!empty($select_categories)): ?>
                                <?php foreach ($select_categories as $category): ?>
                                    <option value="<?= $category['id'] ?>"
                                        <?= isset($oldCate) && $oldCate == $category['id'] ? 'selected' : '' ?>>
                                        <?= $category['name'] ?>
                                    </option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>
                        <?php if(!empty($errCategory)): ?>
                            <span class="text-danger"><?= $errCategory ?></span>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label for="price">Price</label>
                        <input type="number" class="form-control" name="price" value="<?= $oldPrice ?? '' ?>">
                        <?php if(!empty($errPrice)): ?>
                            <span class="text-danger"><?= $errPrice ?></span>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label for="status">Status: </label>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="status" id="statusY" value="Y" checked>
                            <label class="form-check-label" for="statusY">Y</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="status" id="statusN" value="N">
                            <label class="form-check-label" for="statusN">N</label>
                        </div>
                        <?php if(!empty($errStatus)): ?>
                            <span class="text-danger"><?= $errStatus ?></span>
                        <?php endif; ?>
                    </div>
                    <button type="submit" class="btn btn-success" id="btnSubmit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>